<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\Lpm\Enums;

/**
 * Gets or Sets bankNameCodes
 */
class BankNameCode
{
	const ACERTEMOS = "ACERTEMOS";
	const ACCIONES_Y_VALORES = "ACCIONES_Y_VALORES";
	const ACUENTA = "ACUENTA";
	const AGENTE_NIUBIZ = "AGENTE_NIUBIZ";
	const APUESTAS_CUCUTA_75 = "APUESTAS_CUCUTA_75";
	const APUESTAS_UNIDAS = "APUESTAS_UNIDAS";
	const BANCO_DE_CREDITO = "BANCO_DE_CREDITO";
	const BANCO_ESTADO = "BANCO_ESTADO";
	const BANCO_ESTADO_EXPRESS = "BANCO_ESTADO_EXPRESS";
	const BANCO_NACIONAL_DE_COSTA_RICA = "BANCO_NACIONAL_DE_COSTA_RICA";
	const BANCO_RIPLEY = "BANCO_RIPLEY";
	const BBVA_CONTINENTAL = "BBVA_CONTINENTAL";
	const BRADESCO = "BRADESCO";
	const CAJA_AREQUIPA = "CAJA_AREQUIPA";
	const CAJA_HUANCAYO_PERU = "CAJA_HUANCAYO_PERU";
	const CAJA_TACNA_PERU = "CAJA_TACNA_PERU";
	const CAJA_TRUJILLO_PERU = "CAJA_TRUJILLO_PERU";
	const CAJA_VECINA = "CAJA_VECINA";
	const CREDIBANCO = "CREDIBANCO";
	const DIMONEX = "DIMONEX";
	const EFECTY = "EFECTY";
	const EXPRESS_DE_LIDER = "EXPRESS_DE_LIDER";
	const FULL_CARGA = "FULL_CARGA";
	const GANA = "GANA";
	const GANA_GANA = "GANA_GANA";
	const INTERBANK = "INTERBANK";
	const JER = "JER";
	const KASNET = "KASNET";
	const LA_PERLA = "LA_PERLA";
	const LIDER = "LIDER";
	const LOTERICAS = "LOTERICAS";
	const MOVILRED_COLOMBIA = "MOVILRED_COLOMBIA";
	const PAGA_TODO_PARA_TODO = "PAGA_TODO_PARA_TODO";
	const PUNTO_DE_PAGO = "PUNTO_DE_PAGO";
	const PUNTO_RED = "PUNTO_RED";
	const REDEBAN = "REDEBAN";
	const SCOTIABANK = "SCOTIABANK";
	const SUCHANCE = "SUCHANCE";
	const SURED = "SURED";
	const TAMBO = "TAMBO";
	const WALMART_CHILE = "WALMART_CHILE";
	const WESTERN_UNION = "WESTERN_UNION";


}
