<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\Verification;

use Paysafe\PhpSdk\Model\BaseModel;
use Paysafe\PhpSdk\Model\Card\ThreeDs\Authentication;
use Paysafe\PhpSdk\Model\Common\GatewayResponse;
use Paysafe\PhpSdk\Model\Common\PaymentFacilitator\PaymentFacilitator;
use Paysafe\PhpSdk\Model\Common\Profile\Profile;

/**
 * Contains details of a verification for a specific payment type.
 */
class Verification extends BaseModel
{

	private string $merchantRefNum;
	private string $paymentHandleToken;
	private string $customerIp;
	private bool $dupCheck = true;
	private string $description;
	private PaymentFacilitator $paymentFacilitator;
	private string $id;
	private string $txnTime;
	private VerificationPaymentType $paymentType;
	private VerificationStatus $status;
	private string $currencyCode;
	private ?array $riskReasonCode = null;
	private GatewayResponse $gatewayResponse;
	private Profile $profile;
	private Authentication $authentication;

	/**
	 * Builder function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return $this
	 */
	public function merchantRefNum(string $merchantRefNum): self
	{
		$this->setMerchantRefNum($merchantRefNum);
		
		return $this;
	}

	/**
	 * Setter function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return void
	 */
	public function setMerchantRefNum(string $merchantRefNum): void
	{
		$this->merchantRefNum = $merchantRefNum;
	}

	/**
	 * This is the merchant reference number created by the merchant and submitted as part of the request.
	 * 
	 * @return string
	 */
	public function getMerchantRefNum(): string
	{
		return $this->merchantRefNum;
	}

	/**
	 * Builder function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return $this
	 */
	public function paymentHandleToken(string $paymentHandleToken): self
	{
		$this->setPaymentHandleToken($paymentHandleToken);
		
		return $this;
	}

	/**
	 * Setter function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return void
	 */
	public function setPaymentHandleToken(string $paymentHandleToken): void
	{
		$this->paymentHandleToken = $paymentHandleToken;
	}

	/**
	 * This is the payment token generated by Paysafe that will be used for the Verification request.
	 * 
	 * @return string
	 */
	public function getPaymentHandleToken(): string
	{
		return $this->paymentHandleToken;
	}

	/**
	 * Builder function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return $this
	 */
	public function customerIp(string $customerIp): self
	{
		$this->setCustomerIp($customerIp);
		
		return $this;
	}

	/**
	 * Setter function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return void
	 */
	public function setCustomerIp(string $customerIp): void
	{
		$this->customerIp = $customerIp;
	}

	/**
	 * This is the customer's IP address.
	 * 
	 * @return string
	 */
	public function getCustomerIp(): string
	{
		return $this->customerIp;
	}

	/**
	 * Builder function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return $this
	 */
	public function dupCheck(bool $dupCheck): self
	{
		$this->setDupCheck($dupCheck);
		
		return $this;
	}

	/**
	 * Setter function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return void
	 */
	public function setDupCheck(bool $dupCheck): void
	{
		$this->dupCheck = $dupCheck;
	}

	/**
	 * This validates that this request is not a duplicate. A request is considered a duplicate
     * if the merchantRefNum has already been used in
	 * a previous request within the past 90 days.
	 * 
	 * @return bool
	 */
	public function getDupCheck(): bool
	{
		return $this->dupCheck;
	}

	/**
	 * Builder function for description
	 * 
	 * @param string $description
	 * 
	 * @return $this
	 */
	public function description(string $description): self
	{
		$this->setDescription($description);
		
		return $this;
	}

	/**
	 * Setter function for description
	 * 
	 * @param string $description
	 * 
	 * @return void
	 */
	public function setDescription(string $description): void
	{
		$this->description = $description;
	}

	/**
	 * This is a description of the transaction, provided by the merchant.
	 * 
	 * @return string
	 */
	public function getDescription(): string
	{
		return $this->description;
	}

	/**
	 * Builder function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return $this
	 */
	public function paymentFacilitator(PaymentFacilitator $paymentFacilitator): self
	{
		$this->setPaymentFacilitator($paymentFacilitator);
		
		return $this;
	}

	/**
	 * Setter function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return void
	 */
	public function setPaymentFacilitator(PaymentFacilitator $paymentFacilitator): void
	{
		$this->paymentFacilitator = $paymentFacilitator;
	}

	/**
	 * Contains information about Payment facilitator.
     * <b>Note:<b> This object is only for Payment facilitator merchants.
	 * 
	 * @return PaymentFacilitator
	 */
	public function getPaymentFacilitator(): PaymentFacilitator
	{
		return $this->paymentFacilitator;
	}

	/**
	 * Builder function for id
	 * 
	 * @param string $id
	 * 
	 * @return $this
	 */
	public function id(string $id): self
	{
		$this->setId($id);
		
		return $this;
	}

	/**
	 * Setter function for id
	 * 
	 * @param string $id
	 * 
	 * @return void
	 */
	public function setId(string $id): void
	{
		$this->id = $id;
	}

	/**
	 * This is the ID returned in the response. This ID can be used for future associated requests,
     * e,g., looking up the Verification.
	 * 
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}

	/**
	 * Builder function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return $this
	 */
	public function txnTime(string $txnTime): self
	{
		$this->setTxnTime($txnTime);
		
		return $this;
	}

	/**
	 * Setter function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return void
	 */
	public function setTxnTime(string $txnTime): void
	{
		$this->txnTime = $txnTime;
	}

	/**
	 * This is the date and time the transaction was processed.
	 * 
	 * @return string
	 */
	public function getTxnTime(): string
	{
		return $this->txnTime;
	}

	/**
	 * Builder function for paymentType
	 * 
	 * @param VerificationPaymentType $paymentType
	 * 
	 * @return $this
	 */
	public function paymentType(VerificationPaymentType $paymentType): self
	{
		$this->setPaymentType($paymentType);
		
		return $this;
	}

	/**
	 * Setter function for paymentType
	 * 
	 * @param VerificationPaymentType $paymentType
	 * 
	 * @return void
	 */
	public function setPaymentType(VerificationPaymentType $paymentType): void
	{
		$this->paymentType = $paymentType;
	}

	/**
	 * This is the payment type associated with the Payment Handle used for this request.
	 * 
	 * @return VerificationPaymentType
	 */
	public function getPaymentType(): VerificationPaymentType
	{
		return $this->paymentType;
	}

	/**
	 * Builder function for status
	 * 
	 * @param VerificationStatus $status
	 * 
	 * @return $this
	 */
	public function status(VerificationStatus $status): self
	{
		$this->setStatus($status);
		
		return $this;
	}

	/**
	 * Setter function for status
	 * 
	 * @param VerificationStatus $status
	 * 
	 * @return void
	 */
	public function setStatus(VerificationStatus $status): void
	{
		$this->status = $status;
	}

	/**
	 * This is the status of the transaction request.
	 * Possible values are:
	 * <li> RECEIVED - A verification request was received from merchant,
     *      but it has not yet been sent to downstream gateway.</li>
	 * <li> ERROR - The verification has errored - failed for non-business reason (non http status 402 error).</li>
	 * <li> FAILED - The verification has failed and the downstream gateway has returned an error
     *      (http status 402) for some business reason.</li>
	 * <li> COMPLETED - The verification was completed successfully.</li>
	 * 
	 * @return VerificationStatus
	 */
	public function getStatus(): VerificationStatus
	{
		return $this->status;
	}

	/**
	 * Builder function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return $this
	 */
	public function currencyCode(string $currencyCode): self
	{
		$this->setCurrencyCode($currencyCode);
		
		return $this;
	}

	/**
	 * Setter function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return void
	 */
	public function setCurrencyCode(string $currencyCode): void
	{
		$this->currencyCode = $currencyCode;
	}

	/**
	 * This is the currency of the merchant account, e.g., USD or CAD. For a full list, see
	 * (<a
     * href="https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes"
     * >Currency Codes</a>).
	 * 
	 * @return string
	 */
	public function getCurrencyCode(): string
	{
		return $this->currencyCode;
	}

	/**
	 * Builder function for riskReasonCode
	 * 
	 * @param int[] $riskReasonCode
	 * 
	 * @return $this
	 */
	public function riskReasonCode(array $riskReasonCode): self
	{
		$this->setRiskReasonCode($riskReasonCode);
		
		return $this;
	}

	/**
	 * Setter function for riskReasonCode
	 * 
	 * @param int[] $riskReasonCode
	 * 
	 * @return void
	 */
	public function setRiskReasonCode(array $riskReasonCode): void
	{
		$this->riskReasonCode = $riskReasonCode;
	}

	/**
	 * An array of integers is returned, displaying the detailed risk reason codes if your transaction was declined.
	 * It is returned only if your account is configured accordingly.
	 * 
	 * @return int[]|null
	 */
	public function getRiskReasonCode(): array
	{
		return $this->riskReasonCode;
	}

	/**
	 * Add new riskReasonCodeItem
	 * 
	 * @param int $riskReasonCodeItem
	 * 
	 * @return $this
	 */
	public function addRiskReasonCodeItem(int $riskReasonCodeItem): self
	{
		if ($this->riskReasonCode === null) {
			$this->setRiskReasonCode([$riskReasonCodeItem]);
			
			return $this;
		}
		
		$riskReasonCode = $this->getRiskReasonCode();
		$riskReasonCode[] = $riskReasonCodeItem;
		$this->setRiskReasonCode($riskReasonCode);
		
		return $this;
	}

	/**
	 * Remove riskReasonCodeItem
	 * 
	 * @param int $riskReasonCodeItem
	 * 
	 * @return $this
	 */
	public function removeRiskReasonCodeItem(int $riskReasonCodeItem): self
	{
		$this->setRiskReasonCode(array_diff($this->getRiskReasonCode(), [$riskReasonCodeItem]));
		
		return $this;
	}

	/**
	 * Builder function for gatewayResponse
	 * 
	 * @param GatewayResponse $gatewayResponse
	 * 
	 * @return $this
	 */
	public function gatewayResponse(GatewayResponse $gatewayResponse): self
	{
		$this->setGatewayResponse($gatewayResponse);
		
		return $this;
	}

	/**
	 * Setter function for gatewayResponse
	 * 
	 * @param GatewayResponse $gatewayResponse
	 * 
	 * @return void
	 */
	public function setGatewayResponse(GatewayResponse $gatewayResponse): void
	{
		$this->gatewayResponse = $gatewayResponse;
	}

	/**
	 * This is the read-only raw response returned by an acquirer or PSP.
	 * 
	 * @return GatewayResponse
	 */
	public function getGatewayResponse(): GatewayResponse
	{
		return $this->gatewayResponse;
	}

	/**
	 * Builder function for profile
	 * 
	 * @param Profile $profile
	 * 
	 * @return $this
	 */
	public function profile(Profile $profile): self
	{
		$this->setProfile($profile);
		
		return $this;
	}

	/**
	 * Setter function for profile
	 * 
	 * @param Profile $profile
	 * 
	 * @return void
	 */
	public function setProfile(Profile $profile): void
	{
		$this->profile = $profile;
	}

	/**
	 * This is customer's profile details.
	 * 
	 * @return Profile
	 */
	public function getProfile(): Profile
	{
		return $this->profile;
	}

	/**
	 * Builder function for authentication
	 * 
	 * @param Authentication $authentication
	 * 
	 * @return $this
	 */
	public function authentication(Authentication $authentication): self
	{
		$this->setAuthentication($authentication);
		
		return $this;
	}

	/**
	 * Setter function for authentication
	 * 
	 * @param Authentication $authentication
	 * 
	 * @return void
	 */
	public function setAuthentication(Authentication $authentication): void
	{
		$this->authentication = $authentication;
	}

	/**
	 * 3D Secure authentication details.
	 * 
	 * @return Authentication
	 */
	public function getAuthentication(): Authentication
	{
		return $this->authentication;
	}

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class Verification {" . PHP_EOL
			. "    merchantRefNum: " . $this->toIndentedString($this->merchantRefNum) . PHP_EOL
			. "    paymentHandleToken: " . $this->toIndentedString($this->paymentHandleToken) . PHP_EOL
			. "    customerIp: " . $this->toIndentedString($this->customerIp) . PHP_EOL
			. "    dupCheck: " . $this->toIndentedString($this->dupCheck) . PHP_EOL
			. "    description: " . $this->toIndentedString($this->description) . PHP_EOL
			. "    paymentFacilitator: " . $this->toIndentedString($this->paymentFacilitator) . PHP_EOL
			. "    id: " . $this->toIndentedString($this->id) . PHP_EOL
			. "    txnTime: " . $this->toIndentedString($this->txnTime) . PHP_EOL
			. "    paymentType: " . $this->toIndentedString($this->paymentType) . PHP_EOL
			. "    status: " . $this->toIndentedString($this->status) . PHP_EOL
			. "    currencyCode: " . $this->toIndentedString($this->currencyCode) . PHP_EOL
			. "    riskReasonCode: " . $this->toIndentedString($this->riskReasonCode) . PHP_EOL
			. "    gatewayResponse: " . $this->toIndentedString($this->gatewayResponse) . PHP_EOL
			. "    profile: " . $this->toIndentedString($this->profile) . PHP_EOL
			. "    authentication: " . $this->toIndentedString($this->authentication) . PHP_EOL
			. "}";
	}
}
