<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\Verification;

use Paysafe\PhpSdk\Model\BaseModel;
use Paysafe\PhpSdk\Model\Common\PaymentFacilitator\PaymentFacilitator;

/**
 * Contains internal details to be passed in the verification request.
 * Verification allows merchants to validate a credit card without charging any amount on the card.
 * <ul>
 *   <li>
 *     <b>merchantRefNum:</b> Required. This is the merchant reference number created by
 *      the merchant and submitted as part of the request. <br />
 *     Example: 2ca14f87ff6f60976d18
 *   </li>
 *   <li>
 *     <b>paymentHandleToken:</b> Required. This is the payment token generated by Paysafe that will be used
 *      for the Verification request. <br />
 *     Example: 842778a0-03a2-11e9-8eb2-f2801f1b9fd1
 *   </li>
 *   <li>
 *     <b>customerIp:</b> This is the customer's IP address. <br />
 *     Example: 111.111.111.111
 *   </li>
 *   <li>
 *     <b>dupCheck:</b> This validates that this request is not a duplicate. A request is considered a duplicate
 *      if the merchantRefNum
 *     has already been used in a previous request within the past 90 days. <br/>
 *     Default: true
 *   </li>
 *   <li>
 *     <b>description:</b> This is a description of the transaction, provided by the merchant. <br />
 *     Example: Consumer Card Verification
 *   </li>
 *   <li>
 *     <b>paymentFacilitator:</b> Contains information about Payment facilitator. <br />
 *     <b>Note:</b> This object is only for Payment facilitator merchants.
 *   </li>
 * </ul>
 */
class VerificationRequest extends BaseModel
{

	private string $merchantRefNum;
	private string $paymentHandleToken;
	private string $customerIp;
	private bool $dupCheck = true;
	private string $description;
	private PaymentFacilitator $paymentFacilitator;
	private array $additionalParameters;

	/**
	 * Builder function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return $this
	 */
	public function merchantRefNum(string $merchantRefNum): self
	{
		$this->setMerchantRefNum($merchantRefNum);
		
		return $this;
	}

	/**
	 * Setter function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return void
	 */
	public function setMerchantRefNum(string $merchantRefNum): void
	{
		$this->merchantRefNum = $merchantRefNum;
	}

	/**
	 * This is the merchant reference number created by the merchant and submitted as part of the request.
	 * 
	 * @return string
	 */
	public function getMerchantRefNum(): string
	{
		return $this->merchantRefNum;
	}

	/**
	 * Builder function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return $this
	 */
	public function paymentHandleToken(string $paymentHandleToken): self
	{
		$this->setPaymentHandleToken($paymentHandleToken);
		
		return $this;
	}

	/**
	 * Setter function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return void
	 */
	public function setPaymentHandleToken(string $paymentHandleToken): void
	{
		$this->paymentHandleToken = $paymentHandleToken;
	}

	/**
	 * This is the payment token generated by Paysafe that will be used for the Verification request.
	 * 
	 * @return string
	 */
	public function getPaymentHandleToken(): string
	{
		return $this->paymentHandleToken;
	}

	/**
	 * Builder function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return $this
	 */
	public function customerIp(string $customerIp): self
	{
		$this->setCustomerIp($customerIp);
		
		return $this;
	}

	/**
	 * Setter function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return void
	 */
	public function setCustomerIp(string $customerIp): void
	{
		$this->customerIp = $customerIp;
	}

	/**
	 * This is the customer's IP address.
	 * 
	 * @return string
	 */
	public function getCustomerIp(): string
	{
		return $this->customerIp;
	}

	/**
	 * Builder function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return $this
	 */
	public function dupCheck(bool $dupCheck): self
	{
		$this->setDupCheck($dupCheck);
		
		return $this;
	}

	/**
	 * Setter function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return void
	 */
	public function setDupCheck(bool $dupCheck): void
	{
		$this->dupCheck = $dupCheck;
	}

	/**
	 * This validates that this request is not a duplicate. A request is considered a duplicate
     * if the merchantRefNum has already been used in a previous
	 * request within the past 90 days.
	 * 
	 * @return bool
	 */
	public function getDupCheck(): bool
	{
		return $this->dupCheck;
	}

	/**
	 * Builder function for description
	 * 
	 * @param string $description
	 * 
	 * @return $this
	 */
	public function description(string $description): self
	{
		$this->setDescription($description);
		
		return $this;
	}

	/**
	 * Setter function for description
	 * 
	 * @param string $description
	 * 
	 * @return void
	 */
	public function setDescription(string $description): void
	{
		$this->description = $description;
	}

	/**
	 * This is a description of the transaction, provided by the merchant.
	 * 
	 * @return string
	 */
	public function getDescription(): string
	{
		return $this->description;
	}

	/**
	 * Builder function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return $this
	 */
	public function paymentFacilitator(PaymentFacilitator $paymentFacilitator): self
	{
		$this->setPaymentFacilitator($paymentFacilitator);
		
		return $this;
	}

	/**
	 * Setter function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return void
	 */
	public function setPaymentFacilitator(PaymentFacilitator $paymentFacilitator): void
	{
		$this->paymentFacilitator = $paymentFacilitator;
	}

	/**
	 * Contains information about Payment facilitator.
     * <b>Note:<b> This object is only for Payment facilitator merchants.
	 * 
	 * @return PaymentFacilitator
	 */
	public function getPaymentFacilitator(): PaymentFacilitator
	{
		return $this->paymentFacilitator;
	}

	/**
	 * Builder function for additionalParameters
	 * 
	 * @param array $additionalParameters
	 * 
	 * @return $this
	 */
	public function additionalParameters(array $additionalParameters): self
	{
		$this->setAdditionalParameters($additionalParameters);
		
		return $this;
	}

	/**
	 * Setter function for additionalParameters
	 * 
	 * @param array $additionalParameters
	 * 
	 * @return void
	 */
	public function setAdditionalParameters(array $additionalParameters): void
	{
		$this->additionalParameters = $additionalParameters;
	}

	/**
	 * Getter function for additionalParameters
	 * 
	 * @return array
	 */
	public function getAdditionalParameters(): array
	{
		return $this->additionalParameters;
	}

    /**
     * Add a new additional parameter
     *
     * @param string $key
     * @param object $value
     *
     * @return $this
     */
    public function addAdditionalParameter(string $key, object $value): self
    {
        if ($this->additionalParameters === null) {
            $this->additionalParameters = [];
        }

        $this->additionalParameters[$key] = $value;

        return $this;
    }

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class VerificationRequest {" . PHP_EOL
			. "    merchantRefNum: " . $this->toIndentedString($this->merchantRefNum) . PHP_EOL
			. "    paymentHandleToken: " . $this->toIndentedString($this->paymentHandleToken) . PHP_EOL
			. "    customerIp: " . $this->toIndentedString($this->customerIp) . PHP_EOL
			. "    dupCheck: " . $this->toIndentedString($this->dupCheck) . PHP_EOL
			. "    description: " . $this->toIndentedString($this->description) . PHP_EOL
			. "    paymentFacilitator: " . $this->toIndentedString($this->paymentFacilitator) . PHP_EOL
			. "    additionalParameters: " . $this->toIndentedString($this->additionalParameters) . PHP_EOL
			. "}";
	}
}
