<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\Lpm;

use Paysafe\PhpSdk\Model\BaseModel;

/**
 * This contains parameters returned by Skrill gateway
 */
class SkrillPaymentGatewayResponse extends BaseModel
{

	private string $transactionId;
	private string $amount;
	private string $mbTransactionId;
	private string $payFromEmail;
	private string $payToEmail;
	private string $currency;
	private string $merchantId;
	private string $id;
	private string $processor;
	private string $status;
	private string $sid;

	/**
	 * Builder function for transactionId
	 * 
	 * @param string $transactionId
	 * 
	 * @return $this
	 */
	public function transactionId(string $transactionId): self
	{
		$this->setTransactionId($transactionId);
		
		return $this;
	}

	/**
	 * Setter function for transactionId
	 * 
	 * @param string $transactionId
	 * 
	 * @return void
	 */
	public function setTransactionId(string $transactionId): void
	{
		$this->transactionId = $transactionId;
	}

	/**
	 * This transaction id is generated by Paysafe Gateway
	 * 
	 * @return string
	 */
	public function getTransactionId(): string
	{
		return $this->transactionId;
	}

	/**
	 * Builder function for amount
	 * 
	 * @param string $amount
	 * 
	 * @return $this
	 */
	public function amount(string $amount): self
	{
		$this->setAmount($amount);
		
		return $this;
	}

	/**
	 * Setter function for amount
	 * 
	 * @param string $amount
	 * 
	 * @return void
	 */
	public function setAmount(string $amount): void
	{
		$this->amount = $amount;
	}

	/**
	 * Transaction amount
	 * 
	 * @return string
	 */
	public function getAmount(): string
	{
		return $this->amount;
	}

	/**
	 * Builder function for mbTransactionId
	 * 
	 * @param string $mbTransactionId
	 * 
	 * @return $this
	 */
	public function mbTransactionId(string $mbTransactionId): self
	{
		$this->setMbTransactionId($mbTransactionId);
		
		return $this;
	}

	/**
	 * Setter function for mbTransactionId
	 * 
	 * @param string $mbTransactionId
	 * 
	 * @return void
	 */
	public function setMbTransactionId(string $mbTransactionId): void
	{
		$this->mbTransactionId = $mbTransactionId;
	}

	/**
	 * Unique transaction id at Skrill end
	 * 
	 * @return string
	 */
	public function getMbTransactionId(): string
	{
		return $this->mbTransactionId;
	}

	/**
	 * Builder function for payFromEmail
	 * 
	 * @param string $payFromEmail
	 * 
	 * @return $this
	 */
	public function payFromEmail(string $payFromEmail): self
	{
		$this->setPayFromEmail($payFromEmail);
		
		return $this;
	}

	/**
	 * Setter function for payFromEmail
	 * 
	 * @param string $payFromEmail
	 * 
	 * @return void
	 */
	public function setPayFromEmail(string $payFromEmail): void
	{
		$this->payFromEmail = $payFromEmail;
	}

	/**
	 * Customer email using which Payment has been completed
	 * 
	 * @return string
	 */
	public function getPayFromEmail(): string
	{
		return $this->payFromEmail;
	}

	/**
	 * Builder function for payToEmail
	 * 
	 * @param string $payToEmail
	 * 
	 * @return $this
	 */
	public function payToEmail(string $payToEmail): self
	{
		$this->setPayToEmail($payToEmail);
		
		return $this;
	}

	/**
	 * Setter function for payToEmail
	 * 
	 * @param string $payToEmail
	 * 
	 * @return void
	 */
	public function setPayToEmail(string $payToEmail): void
	{
		$this->payToEmail = $payToEmail;
	}

	/**
	 * Merchant's email
	 * 
	 * @return string
	 */
	public function getPayToEmail(): string
	{
		return $this->payToEmail;
	}

	/**
	 * Builder function for currency
	 * 
	 * @param string $currency
	 * 
	 * @return $this
	 */
	public function currency(string $currency): self
	{
		$this->setCurrency($currency);
		
		return $this;
	}

	/**
	 * Setter function for currency
	 * 
	 * @param string $currency
	 * 
	 * @return void
	 */
	public function setCurrency(string $currency): void
	{
		$this->currency = $currency;
	}

	/**
	 * Transaction currency
	 * 
	 * @return string
	 */
	public function getCurrency(): string
	{
		return $this->currency;
	}

	/**
	 * Builder function for merchantId
	 * 
	 * @param string $merchantId
	 * 
	 * @return $this
	 */
	public function merchantId(string $merchantId): self
	{
		$this->setMerchantId($merchantId);
		
		return $this;
	}

	/**
	 * Setter function for merchantId
	 * 
	 * @param string $merchantId
	 * 
	 * @return void
	 */
	public function setMerchantId(string $merchantId): void
	{
		$this->merchantId = $merchantId;
	}

	/**
	 * Skrill Merchant ID
	 * 
	 * @return string
	 */
	public function getMerchantId(): string
	{
		return $this->merchantId;
	}

	/**
	 * Builder function for id
	 * 
	 * @param string $id
	 * 
	 * @return $this
	 */
	public function id(string $id): self
	{
		$this->setId($id);
		
		return $this;
	}

	/**
	 * Setter function for id
	 * 
	 * @param string $id
	 * 
	 * @return void
	 */
	public function setId(string $id): void
	{
		$this->id = $id;
	}

	/**
	 * This is same as \"mb_transaction_id\"
	 * 
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}

	/**
	 * Builder function for processor
	 * 
	 * @param string $processor
	 * 
	 * @return $this
	 */
	public function processor(string $processor): self
	{
		$this->setProcessor($processor);
		
		return $this;
	}

	/**
	 * Setter function for processor
	 * 
	 * @param string $processor
	 * 
	 * @return void
	 */
	public function setProcessor(string $processor): void
	{
		$this->processor = $processor;
	}

	/**
	 * This is the processor. Possible value: SKRILL_QCO
	 * 
	 * @return string
	 */
	public function getProcessor(): string
	{
		return $this->processor;
	}

	/**
	 * Builder function for status
	 * 
	 * @param string $status
	 * 
	 * @return $this
	 */
	public function status(string $status): self
	{
		$this->setStatus($status);
		
		return $this;
	}

	/**
	 * Setter function for status
	 * 
	 * @param string $status
	 * 
	 * @return void
	 */
	public function setStatus(string $status): void
	{
		$this->status = $status;
	}

	/**
	 * Status of the transaction at Skrill end. Possible values:<br />
	 * • 2 - Success <br />
	 * • 0 - Pending <br />
	 * • -2 - Failed
	 * 
	 * @return string
	 */
	public function getStatus(): string
	{
		return $this->status;
	}

	/**
	 * Builder function for sid
	 * 
	 * @param string $sid
	 * 
	 * @return $this
	 */
	public function sid(string $sid): self
	{
		$this->setSid($sid);
		
		return $this;
	}

	/**
	 * Setter function for sid
	 * 
	 * @param string $sid
	 * 
	 * @return void
	 */
	public function setSid(string $sid): void
	{
		$this->sid = $sid;
	}

	/**
	 * Skrll session id during which transaction is completed
	 * 
	 * @return string
	 */
	public function getSid(): string
	{
		return $this->sid;
	}

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class SkrillPaymentGatewayResponse {" . PHP_EOL
			. "    transactionId: " . $this->toIndentedString($this->transactionId) . PHP_EOL
			. "    amount: " . $this->toIndentedString($this->amount) . PHP_EOL
			. "    mbTransactionId: " . $this->toIndentedString($this->mbTransactionId) . PHP_EOL
			. "    payFromEmail: " . $this->toIndentedString($this->payFromEmail) . PHP_EOL
			. "    payToEmail: " . $this->toIndentedString($this->payToEmail) . PHP_EOL
			. "    currency: " . $this->toIndentedString($this->currency) . PHP_EOL
			. "    merchantId: " . $this->toIndentedString($this->merchantId) . PHP_EOL
			. "    id: " . $this->toIndentedString($this->id) . PHP_EOL
			. "    processor: " . $this->toIndentedString($this->processor) . PHP_EOL
			. "    status: " . $this->toIndentedString($this->status) . PHP_EOL
			. "    sid: " . $this->toIndentedString($this->sid) . PHP_EOL
			. "}";
	}
}
