<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\StandaloneCredit;

use Paysafe\PhpSdk\Model\BaseModel;
use Paysafe\PhpSdk\Model\Card\Card;
use Paysafe\PhpSdk\Model\Card\MerchantDescriptor;
use Paysafe\PhpSdk\Model\Common\BillingDetails;
use Paysafe\PhpSdk\Model\Common\PaymentFacilitator\PaymentFacilitator;
use Paysafe\PhpSdk\Model\Common\Profile\Profile;
use Paysafe\PhpSdk\Model\Common\ReturnLink;
use Paysafe\PhpSdk\Model\Lpm\Interac;

/**
 * StandaloneCredit
 */
class StandaloneCredit extends BaseModel
{

	private string $merchantRefNum;
	private string $paymentHandleToken;
	private int $amount;
	private string $currencyCode;
	private string $customerIp;
	private bool $onHold = true;
	private string $description;
	private bool $dupCheck = true;
	private MerchantDescriptor $merchantDescriptor;
	private PaymentFacilitator $paymentFacilitator;
	private Sender $sender;
	private string $sourceOfFunds;
	private string $id;
	private string $cardSchemeTransactionId;
	private string $paymentType;
	private string $txnTime;
	private BillingDetails $billingDetails;
	private string $status;
	private array $returnLinks;
	private bool $liveMode;
	private string $updatedTime;
	private string $statusTime;
	private Profile $profile;
	private string $transactionIntent;
	private string $gatewayReconciliationId;
	private Card $card;
	private Interac $interacEtransfer;

	/**
	 * Builder function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return $this
	 */
	public function merchantRefNum(string $merchantRefNum): self
	{
		$this->setMerchantRefNum($merchantRefNum);
		
		return $this;
	}

	/**
	 * Setter function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return void
	 */
	public function setMerchantRefNum(string $merchantRefNum): void
	{
		$this->merchantRefNum = $merchantRefNum;
	}

	/**
	 * This is the merchant reference number created by  the merchant and submitted as part of the request.
     * It must be unique for each request.
	 * 
	 * @return string
	 */
	public function getMerchantRefNum(): string
	{
		return $this->merchantRefNum;
	}

	/**
	 * Builder function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return $this
	 */
	public function paymentHandleToken(string $paymentHandleToken): self
	{
		$this->setPaymentHandleToken($paymentHandleToken);
		
		return $this;
	}

	/**
	 * Setter function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return void
	 */
	public function setPaymentHandleToken(string $paymentHandleToken): void
	{
		$this->paymentHandleToken = $paymentHandleToken;
	}

	/**
	 * This is the payment token generated by Paysafe that will be used for the request.
	 * 
	 * @return string
	 */
	public function getPaymentHandleToken(): string
	{
		return $this->paymentHandleToken;
	}

	/**
	 * Builder function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return $this
	 */
	public function amount(int $amount): self
	{
		$this->setAmount($amount);
		
		return $this;
	}

	/**
	 * Setter function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return void
	 */
	public function setAmount(int $amount): void
	{
		$this->amount = $amount;
	}

	/**
	 * This is the amount of the request, in minor units. For example, to process US $10.99, this value
     * should be 1099. <br />
	 * <b>Note:<b> The amount specified in the Credit request must match the amount specified in the Payment
     * Handle request from which the
	 * paymentHandleToken is taken.
	 * 
	 * @return int
	 */
	public function getAmount(): int
	{
		return $this->amount;
	}

	/**
	 * Builder function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return $this
	 */
	public function currencyCode(string $currencyCode): self
	{
		$this->setCurrencyCode($currencyCode);
		
		return $this;
	}

	/**
	 * Setter function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return void
	 */
	public function setCurrencyCode(string $currencyCode): void
	{
		$this->currencyCode = $currencyCode;
	}

	/**
	 * This is the currency of the merchant account, for example, USD or CAD. See
	 * <a
     * href="https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes"
     * >Currency Codes.</a>
	 * <br />
	 * <b>Note:<b> The currencyCode specified in the Credit request must match the currencyCode specified
     * in the Payment Handle request
	 * from which the paymentHandleToken is taken.
	 * 
	 * @return string
	 */
	public function getCurrencyCode(): string
	{
		return $this->currencyCode;
	}

	/**
	 * Builder function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return $this
	 */
	public function customerIp(string $customerIp): self
	{
		$this->setCustomerIp($customerIp);
		
		return $this;
	}

	/**
	 * Setter function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return void
	 */
	public function setCustomerIp(string $customerIp): void
	{
		$this->customerIp = $customerIp;
	}

	/**
	 * This is the customer's IP address.
	 * 
	 * @return string
	 */
	public function getCustomerIp(): string
	{
		return $this->customerIp;
	}

	/**
	 * Builder function for onHold
	 * 
	 * @param bool $onHold
	 * 
	 * @return $this
	 */
	public function onHold(bool $onHold): self
	{
		$this->setOnHold($onHold);
		
		return $this;
	}

	/**
	 * Setter function for onHold
	 * 
	 * @param bool $onHold
	 * 
	 * @return void
	 */
	public function setOnHold(bool $onHold): void
	{
		$this->onHold = $onHold;
	}

	/**
	 * This parameter can be used by merchants to hold the SCT for additional checks on their end.
	 * 
	 * @return bool
	 */
	public function getOnHold(): bool
	{
		return $this->onHold;
	}

	/**
	 * Builder function for description
	 * 
	 * @param string $description
	 * 
	 * @return $this
	 */
	public function description(string $description): self
	{
		$this->setDescription($description);
		
		return $this;
	}

	/**
	 * Setter function for description
	 * 
	 * @param string $description
	 * 
	 * @return void
	 */
	public function setDescription(string $description): void
	{
		$this->description = $description;
	}

	/**
	 * This is a description of the transaction, provided by the merchant.
	 * 
	 * @return string
	 */
	public function getDescription(): string
	{
		return $this->description;
	}

	/**
	 * Builder function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return $this
	 */
	public function dupCheck(bool $dupCheck): self
	{
		$this->setDupCheck($dupCheck);
		
		return $this;
	}

	/**
	 * Setter function for dupCheck
	 * 
	 * @param bool $dupCheck
	 * 
	 * @return void
	 */
	public function setDupCheck(bool $dupCheck): void
	{
		$this->dupCheck = $dupCheck;
	}

	/**
	 * This validates that this request is not a duplicate. A duplicate request is when the merchantRefNum
     * has already been used in a previous request
	 * within the past 90 days.
	 * 
	 * @return bool
	 */
	public function getDupCheck(): bool
	{
		return $this->dupCheck;
	}

	/**
	 * Builder function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return $this
	 */
	public function merchantDescriptor(MerchantDescriptor $merchantDescriptor): self
	{
		$this->setMerchantDescriptor($merchantDescriptor);
		
		return $this;
	}

	/**
	 * Setter function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return void
	 */
	public function setMerchantDescriptor(MerchantDescriptor $merchantDescriptor): void
	{
		$this->merchantDescriptor = $merchantDescriptor;
	}

	/**
	 * For Card payment method only. This is the merchant descriptor that will be displayed on
     * the customer's card or bank statement.
	 * 
	 * @return MerchantDescriptor
	 */
	public function getMerchantDescriptor(): MerchantDescriptor
	{
		return $this->merchantDescriptor;
	}

	/**
	 * Builder function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return $this
	 */
	public function paymentFacilitator(PaymentFacilitator $paymentFacilitator): self
	{
		$this->setPaymentFacilitator($paymentFacilitator);
		
		return $this;
	}

	/**
	 * Setter function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return void
	 */
	public function setPaymentFacilitator(PaymentFacilitator $paymentFacilitator): void
	{
		$this->paymentFacilitator = $paymentFacilitator;
	}

	/**
	 * Contains information about Payment facilitator.
     * <b>Note:<b> This object is only for Payment facilitator merchants.
	 * 
	 * @return PaymentFacilitator
	 */
	public function getPaymentFacilitator(): PaymentFacilitator
	{
		return $this->paymentFacilitator;
	}

	/**
	 * Builder function for sender
	 * 
	 * @param Sender $sender
	 * 
	 * @return $this
	 */
	public function sender(Sender $sender): self
	{
		$this->setSender($sender);
		
		return $this;
	}

	/**
	 * Setter function for sender
	 * 
	 * @param Sender $sender
	 * 
	 * @return void
	 */
	public function setSender(Sender $sender): void
	{
		$this->sender = $sender;
	}

	/**
	 * The Sender is deemed to be the person or party who has the contractual relationship with the end customer.
	 * <b>Note: </b> In case of Visa Direct with use cases Account to Account, Wallet transfer or Funds Transfer,
	 * the sender name should be the same as the recipient name.
	 * 
	 * @return Sender
	 */
	public function getSender(): Sender
	{
		return $this->sender;
	}

	/**
	 * Builder function for sourceOfFunds
	 * 
	 * @param string $sourceOfFunds
	 * 
	 * @return $this
	 */
	public function sourceOfFunds(string $sourceOfFunds): self
	{
		$this->setSourceOfFunds($sourceOfFunds);
		
		return $this;
	}

	/**
	 * Setter function for sourceOfFunds
	 * 
	 * @param string $sourceOfFunds
	 * 
	 * @return void
	 */
	public function setSourceOfFunds(string $sourceOfFunds): void
	{
		$this->sourceOfFunds = $sourceOfFunds;
	}

	/**
	 * This field contains the information representing the payment transaction funding source.
     * Possible values: <br />
	 * • Credit <br />
	 * • Debit <br />
	 * • Prepaid <br />
	 * • Cash <br />
	 * • Deposit account <br />
	 * • Credit account <br />
	 * • Mobile money account
	 * 
	 * @return string
	 */
	public function getSourceOfFunds(): string
	{
		return $this->sourceOfFunds;
	}

	/**
	 * Builder function for id
	 * 
	 * @param string $id
	 * 
	 * @return $this
	 */
	public function id(string $id): self
	{
		$this->setId($id);
		
		return $this;
	}

	/**
	 * Setter function for id
	 * 
	 * @param string $id
	 * 
	 * @return void
	 */
	public function setId(string $id): void
	{
		$this->id = $id;
	}

	/**
	 * This is the ID returned in the response. This ID can be used for future associated requests.
	 * 
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}

	/**
	 * Builder function for cardSchemeTransactionId
	 * 
	 * @param string $cardSchemeTransactionId
	 * 
	 * @return $this
	 */
	public function cardSchemeTransactionId(string $cardSchemeTransactionId): self
	{
		$this->setCardSchemeTransactionId($cardSchemeTransactionId);
		
		return $this;
	}

	/**
	 * Setter function for cardSchemeTransactionId
	 * 
	 * @param string $cardSchemeTransactionId
	 * 
	 * @return void
	 */
	public function setCardSchemeTransactionId(string $cardSchemeTransactionId): void
	{
		$this->cardSchemeTransactionId = $cardSchemeTransactionId;
	}

	/**
	 * This is the ID returned in the response. This ID can be used for future associated requests.
	 * 
	 * @return string
	 */
	public function getCardSchemeTransactionId(): string
	{
		return $this->cardSchemeTransactionId;
	}

	/**
	 * Builder function for paymentType
	 * 
	 * @param string $paymentType
	 * 
	 * @return $this
	 */
	public function paymentType(string $paymentType): self
	{
		$this->setPaymentType($paymentType);
		
		return $this;
	}

	/**
	 * Setter function for paymentType
	 * 
	 * @param string $paymentType
	 * 
	 * @return void
	 */
	public function setPaymentType(string $paymentType): void
	{
		$this->paymentType = $paymentType;
	}

	/**
	 * This is the payment type associated with the Payment Handle used for this request.<br />
	 * 
	 * @return string
	 */
	public function getPaymentType(): string
	{
		return $this->paymentType;
	}

	/**
	 * Builder function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return $this
	 */
	public function txnTime(string $txnTime): self
	{
		$this->setTxnTime($txnTime);
		
		return $this;
	}

	/**
	 * Setter function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return void
	 */
	public function setTxnTime(string $txnTime): void
	{
		$this->txnTime = $txnTime;
	}

	/**
	 * This is the date and time the transaction was processed.
	 * 
	 * @return string
	 */
	public function getTxnTime(): string
	{
		return $this->txnTime;
	}

	/**
	 * Builder function for billingDetails
	 * 
	 * @param BillingDetails $billingDetails
	 * 
	 * @return $this
	 */
	public function billingDetails(BillingDetails $billingDetails): self
	{
		$this->setBillingDetails($billingDetails);
		
		return $this;
	}

	/**
	 * Setter function for billingDetails
	 * 
	 * @param BillingDetails $billingDetails
	 * 
	 * @return void
	 */
	public function setBillingDetails(BillingDetails $billingDetails): void
	{
		$this->billingDetails = $billingDetails;
	}

	/**
	 * Customer's billing details. Required if AVS (Address verification) is enabled.<br />
	 * If included in the request, this will serve as the billing address for transaction processing. <br />
	 * Any billing details returned in Apple Pay Token by Apple Pay will be ignored. <br />
	 * 3DS Flow: It is recommended to send billingDetails to improve acceptance rate.
	 * 
	 * @return BillingDetails
	 */
	public function getBillingDetails(): BillingDetails
	{
		return $this->billingDetails;
	}

	/**
	 * Builder function for status
	 * 
	 * @param string $status
	 * 
	 * @return $this
	 */
	public function status(string $status): self
	{
		$this->setStatus($status);
		
		return $this;
	}

	/**
	 * Setter function for status
	 * 
	 * @param string $status
	 * 
	 * @return void
	 */
	public function setStatus(string $status): void
	{
		$this->status = $status;
	}

	/**
	 * This is the status of the payment handle. Possible values are: <br />
	 * • INITIATED – The transaction was initiated with the downstream provider. <br />
	 * • PENDING - The transaction awaiting payment service provider's response. <br />
	 * • FAILED – The transaction failed due to either an error or being declined. <br />
	 * • CANCELLED - The authorization request has been fully reversed. <br />
	 * • EXPIRED – The transaction request is expired. <br />
	 * • COMPLETED – The transaction request is completed. <br />
	 * • RECEIVED – Our system has received the request and is waiting for the downstream processor’s response.
     * <br />
	 * <p>
	 * 
	 * @return string
	 */
	public function getStatus(): string
	{
		return $this->status;
	}

	/**
	 * Builder function for returnLinks
	 * 
	 * @param ReturnLink[] $returnLinks
	 * 
	 * @return $this
	 */
	public function returnLinks(array $returnLinks): self
	{
		$this->setReturnLinks($returnLinks);
		
		return $this;
	}

	/**
	 * Setter function for returnLinks
	 * 
	 * @param ReturnLink[] $returnLinks
	 * 
	 * @return void
	 */
	public function setReturnLinks(array $returnLinks): void
	{
		$this->returnLinks = $returnLinks;
	}

	/**
	 * The URL endpoints to redirect the customer to after a redirection to an alternative payment or 3D Secure site.
	 * You can customize the return URL based on the transaction status.
	 * 
	 * @return ReturnLink[]
	 */
	public function getReturnLinks(): array
	{
		return $this->returnLinks;
	}

	/**
	 * Add new returnLinksItem
	 * 
	 * @param ReturnLink $returnLinksItem
	 * 
	 * @return $this
	 */
	public function addReturnLinksItem(ReturnLink $returnLinksItem): self
	{
		if ($this->returnLinks === null) {
			$this->setReturnLinks([$returnLinksItem]);
			
			return $this;
		}
		
		$returnLinks = $this->getReturnLinks();
		$returnLinks[] = $returnLinksItem;
		$this->setReturnLinks($returnLinks);
		
		return $this;
	}

	/**
	 * Remove returnLinksItem
	 * 
	 * @param ReturnLink $returnLinksItem
	 * 
	 * @return $this
	 */
	public function removeReturnLinksItem(ReturnLink $returnLinksItem): self
	{
		$this->setReturnLinks(array_diff($this->getReturnLinks(), [$returnLinksItem]));
		
		return $this;
	}

	/**
	 * Builder function for liveMode
	 * 
	 * @param bool $liveMode
	 * 
	 * @return $this
	 */
	public function liveMode(bool $liveMode): self
	{
		$this->setLiveMode($liveMode);
		
		return $this;
	}

	/**
	 * Setter function for liveMode
	 * 
	 * @param bool $liveMode
	 * 
	 * @return void
	 */
	public function setLiveMode(bool $liveMode): void
	{
		$this->liveMode = $liveMode;
	}

	/**
	 * This flag indicates the environment.  - true - Production - false - Non-Production
	 * 
	 * @return bool
	 */
	public function getLiveMode(): bool
	{
		return $this->liveMode;
	}

	/**
	 * Builder function for updatedTime
	 * 
	 * @param string $updatedTime
	 * 
	 * @return $this
	 */
	public function updatedTime(string $updatedTime): self
	{
		$this->setUpdatedTime($updatedTime);
		
		return $this;
	}

	/**
	 * Setter function for updatedTime
	 * 
	 * @param string $updatedTime
	 * 
	 * @return void
	 */
	public function setUpdatedTime(string $updatedTime): void
	{
		$this->updatedTime = $updatedTime;
	}

	/**
	 * ISO 8601 format (UTC). This is the date and time the resource was last updated.
	 * 
	 * @return string
	 */
	public function getUpdatedTime(): string
	{
		return $this->updatedTime;
	}

	/**
	 * Builder function for statusTime
	 * 
	 * @param string $statusTime
	 * 
	 * @return $this
	 */
	public function statusTime(string $statusTime): self
	{
		$this->setStatusTime($statusTime);
		
		return $this;
	}

	/**
	 * Setter function for statusTime
	 * 
	 * @param string $statusTime
	 * 
	 * @return void
	 */
	public function setStatusTime(string $statusTime): void
	{
		$this->statusTime = $statusTime;
	}

	/**
	 * ISO 8601 format (UTC). This is the date and time the resource was last updated.
	 * 
	 * @return string
	 */
	public function getStatusTime(): string
	{
		return $this->statusTime;
	}

	/**
	 * Builder function for profile
	 * 
	 * @param Profile $profile
	 * 
	 * @return $this
	 */
	public function profile(Profile $profile): self
	{
		$this->setProfile($profile);
		
		return $this;
	}

	/**
	 * Setter function for profile
	 * 
	 * @param Profile $profile
	 * 
	 * @return void
	 */
	public function setProfile(Profile $profile): void
	{
		$this->profile = $profile;
	}

	/**
	 * This is customer's profile details.
	 * 
	 * @return Profile
	 */
	public function getProfile(): Profile
	{
		return $this->profile;
	}

	/**
	 * Builder function for transactionIntent
	 * 
	 * @param string $transactionIntent
	 * 
	 * @return $this
	 */
	public function transactionIntent(string $transactionIntent): self
	{
		$this->setTransactionIntent($transactionIntent);
		
		return $this;
	}

	/**
	 * Setter function for transactionIntent
	 * 
	 * @param string $transactionIntent
	 * 
	 * @return void
	 */
	public function setTransactionIntent(string $transactionIntent): void
	{
		$this->transactionIntent = $transactionIntent;
	}

	/**
	 * Get transactionIntent
	 * 
	 * @return string
	 */
	public function getTransactionIntent(): string
	{
		return $this->transactionIntent;
	}

	/**
	 * Builder function for gatewayReconciliationId
	 * 
	 * @param string $gatewayReconciliationId
	 * 
	 * @return $this
	 */
	public function gatewayReconciliationId(string $gatewayReconciliationId): self
	{
		$this->setGatewayReconciliationId($gatewayReconciliationId);
		
		return $this;
	}

	/**
	 * Setter function for gatewayReconciliationId
	 * 
	 * @param string $gatewayReconciliationId
	 * 
	 * @return void
	 */
	public function setGatewayReconciliationId(string $gatewayReconciliationId): void
	{
		$this->gatewayReconciliationId = $gatewayReconciliationId;
	}

	/**
	 * Transaction identifier that can be used to reconcile this transaction with the provider gateway.
	 * 
	 * @return string
	 */
	public function getGatewayReconciliationId(): string
	{
		return $this->gatewayReconciliationId;
	}

	/**
	 * Builder function for card
	 * 
	 * @param Card $card
	 * 
	 * @return $this
	 */
	public function card(Card $card): self
	{
		$this->setCard($card);
		
		return $this;
	}

	/**
	 * Setter function for card
	 * 
	 * @param Card $card
	 * 
	 * @return void
	 */
	public function setCard(Card $card): void
	{
		$this->card = $card;
	}

	/**
	 * Transaction identifier that can be used to reconcile this transaction with the provider gateway.
	 * 
	 * @return Card
	 */
	public function getCard(): Card
	{
		return $this->card;
	}

	/**
	 * Builder function for interacEtransfer
	 * 
	 * @param Interac $interacEtransfer
	 * 
	 * @return $this
	 */
	public function interacEtransfer(Interac $interacEtransfer): self
	{
		$this->setInteracEtransfer($interacEtransfer);
		
		return $this;
	}

	/**
	 * Setter function for interacEtransfer
	 * 
	 * @param Interac $interacEtransfer
	 * 
	 * @return void
	 */
	public function setInteracEtransfer(Interac $interacEtransfer): void
	{
		$this->interacEtransfer = $interacEtransfer;
	}

	/**
	 * Details of the interac E-Transfer used for the transaction.
	 * 
	 * @return Interac
	 */
	public function getInteracEtransfer(): Interac
	{
		return $this->interacEtransfer;
	}

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class StandaloneCredit {" . PHP_EOL
			. "    merchantRefNum: " . $this->toIndentedString($this->merchantRefNum) . PHP_EOL
			. "    paymentHandleToken: " . $this->toIndentedString($this->paymentHandleToken) . PHP_EOL
			. "    amount: " . $this->toIndentedString($this->amount) . PHP_EOL
			. "    currencyCode: " . $this->toIndentedString($this->currencyCode) . PHP_EOL
			. "    customerIp: " . $this->toIndentedString($this->customerIp) . PHP_EOL
			. "    onHold: " . $this->toIndentedString($this->onHold) . PHP_EOL
			. "    description: " . $this->toIndentedString($this->description) . PHP_EOL
			. "    dupCheck: " . $this->toIndentedString($this->dupCheck) . PHP_EOL
			. "    merchantDescriptor: " . $this->toIndentedString($this->merchantDescriptor) . PHP_EOL
			. "    paymentFacilitator: " . $this->toIndentedString($this->paymentFacilitator) . PHP_EOL
			. "    sender: " . $this->toIndentedString($this->sender) . PHP_EOL
			. "    sourceOfFunds: " . $this->toIndentedString($this->sourceOfFunds) . PHP_EOL
			. "    id: " . $this->toIndentedString($this->id) . PHP_EOL
			. "    cardSchemeTransactionId: " . $this->toIndentedString($this->cardSchemeTransactionId) . PHP_EOL
			. "    paymentType: " . $this->toIndentedString($this->paymentType) . PHP_EOL
			. "    txnTime: " . $this->toIndentedString($this->txnTime) . PHP_EOL
			. "    billingDetails: " . $this->toIndentedString($this->billingDetails) . PHP_EOL
			. "    status: " . $this->toIndentedString($this->status) . PHP_EOL
			. "    returnLinks: " . $this->toIndentedString($this->returnLinks) . PHP_EOL
			. "    liveMode: " . $this->toIndentedString($this->liveMode) . PHP_EOL
			. "    updatedTime: " . $this->toIndentedString($this->updatedTime) . PHP_EOL
			. "    statusTime: " . $this->toIndentedString($this->statusTime) . PHP_EOL
			. "    profile: " . $this->toIndentedString($this->profile) . PHP_EOL
			. "    transactionIntent: " . $this->toIndentedString($this->transactionIntent) . PHP_EOL
			. "    gatewayReconciliationId: " . $this->toIndentedString($this->gatewayReconciliationId) . PHP_EOL
			. "    card: " . $this->toIndentedString($this->card) . PHP_EOL
			. "    interacEtransfer: " . $this->toIndentedString($this->interacEtransfer) . PHP_EOL
			. "}";
	}
}
