<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\OriginalCredit;

use Paysafe\PhpSdk\Model\BaseModel;
use Paysafe\PhpSdk\Model\Card\MerchantDescriptor;
use Paysafe\PhpSdk\Model\Common\PaymentFacilitator\PaymentFacilitator;

/**
 * OriginalCreditRequest
 */
class OriginalCreditRequest extends BaseModel
{

	private string $merchantRefNum;
	private int $amount;
	private string $currencyCode;
	private string $paymentHandleToken;
	private string $customerIp;
	private string $description;
	private MerchantDescriptor $merchantDescriptor;
	private PaymentFacilitator $paymentFacilitator;
	private array $additionalParameters;

	/**
	 * Builder function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return $this
	 */
	public function merchantRefNum(string $merchantRefNum): self
	{
		$this->setMerchantRefNum($merchantRefNum);
		
		return $this;
	}

	/**
	 * Setter function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return void
	 */
	public function setMerchantRefNum(string $merchantRefNum): void
	{
		$this->merchantRefNum = $merchantRefNum;
	}

	/**
	 * This is the merchant reference number created by the merchant and submitted as part of the request.
     * It must be unique for each request.
	 * 
	 * @return string
	 */
	public function getMerchantRefNum(): string
	{
		return $this->merchantRefNum;
	}

	/**
	 * Builder function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return $this
	 */
	public function amount(int $amount): self
	{
		$this->setAmount($amount);
		
		return $this;
	}

	/**
	 * Setter function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return void
	 */
	public function setAmount(int $amount): void
	{
		$this->amount = $amount;
	}

	/**
	 * This is the amount of the request, in minor units. For example, to process US $10.99,
     * this value should be 1099.
	 * <b>Note:<b> The amount specified in the Original Credit
	 * request must match the amount specified in the Payment Handle request from which
     * the paymentHandleToken is taken. <br />
	 * Maximum: 99999999999
	 * 
	 * @return int
	 */
	public function getAmount(): int
	{
		return $this->amount;
	}

	/**
	 * Builder function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return $this
	 */
	public function currencyCode(string $currencyCode): self
	{
		$this->setCurrencyCode($currencyCode);
		
		return $this;
	}

	/**
	 * Setter function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return void
	 */
	public function setCurrencyCode(string $currencyCode): void
	{
		$this->currencyCode = $currencyCode;
	}

	/**
	 * This is the currency of the merchant account, e.g., USD or CAD, returned in the request response.
	 * See (
     * <a
     * href="https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes"
     * >Currency Codes.</a>)<br />
	 * <b>Note:<b> The currencyCode specified in the Credit request must match
     * the currencyCode specified in the Payment Handle
	 * request from which the paymentHandleToken is taken.
	 * 
	 * @return string
	 */
	public function getCurrencyCode(): string
	{
		return $this->currencyCode;
	}

	/**
	 * Builder function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return $this
	 */
	public function paymentHandleToken(string $paymentHandleToken): self
	{
		$this->setPaymentHandleToken($paymentHandleToken);
		
		return $this;
	}

	/**
	 * Setter function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return void
	 */
	public function setPaymentHandleToken(string $paymentHandleToken): void
	{
		$this->paymentHandleToken = $paymentHandleToken;
	}

	/**
	 * This is the payment token generated by Paysafe that will be used by merchants for Original Credit requests.
	 * 
	 * @return string
	 */
	public function getPaymentHandleToken(): string
	{
		return $this->paymentHandleToken;
	}

	/**
	 * Builder function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return $this
	 */
	public function customerIp(string $customerIp): self
	{
		$this->setCustomerIp($customerIp);
		
		return $this;
	}

	/**
	 * Setter function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return void
	 */
	public function setCustomerIp(string $customerIp): void
	{
		$this->customerIp = $customerIp;
	}

	/**
	 * This is the customer's IP address.
	 * 
	 * @return string
	 */
	public function getCustomerIp(): string
	{
		return $this->customerIp;
	}

	/**
	 * Builder function for description
	 * 
	 * @param string $description
	 * 
	 * @return $this
	 */
	public function description(string $description): self
	{
		$this->setDescription($description);
		
		return $this;
	}

	/**
	 * Setter function for description
	 * 
	 * @param string $description
	 * 
	 * @return void
	 */
	public function setDescription(string $description): void
	{
		$this->description = $description;
	}

	/**
	 * This is a description of the transaction, provided by the merchant.
	 * 
	 * @return string
	 */
	public function getDescription(): string
	{
		return $this->description;
	}

	/**
	 * Builder function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return $this
	 */
	public function merchantDescriptor(MerchantDescriptor $merchantDescriptor): self
	{
		$this->setMerchantDescriptor($merchantDescriptor);
		
		return $this;
	}

	/**
	 * Setter function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return void
	 */
	public function setMerchantDescriptor(MerchantDescriptor $merchantDescriptor): void
	{
		$this->merchantDescriptor = $merchantDescriptor;
	}

	/**
	 * For Card payment method only.
     * This is the merchant descriptor that will
     * be displayed on the customer's card or bank statement.
	 * 
	 * @return MerchantDescriptor
	 */
	public function getMerchantDescriptor(): MerchantDescriptor
	{
		return $this->merchantDescriptor;
	}

	/**
	 * Builder function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return $this
	 */
	public function paymentFacilitator(PaymentFacilitator $paymentFacilitator): self
	{
		$this->setPaymentFacilitator($paymentFacilitator);
		
		return $this;
	}

	/**
	 * Setter function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return void
	 */
	public function setPaymentFacilitator(PaymentFacilitator $paymentFacilitator): void
	{
		$this->paymentFacilitator = $paymentFacilitator;
	}

	/**
	 * Contains information about Payment facilitator.
     * <b>Note:<b> This object is only for Payment facilitator merchants.
	 * 
	 * @return PaymentFacilitator
	 */
	public function getPaymentFacilitator(): PaymentFacilitator
	{
		return $this->paymentFacilitator;
	}

	/**
	 * Builder function for additionalParameters
	 * 
	 * @param array $additionalParameters
	 * 
	 * @return $this
	 */
	public function additionalParameters(array $additionalParameters): self
	{
		$this->setAdditionalParameters($additionalParameters);
		
		return $this;
	}

	/**
	 * Setter function for additionalParameters
	 * 
	 * @param array $additionalParameters
	 * 
	 * @return void
	 */
	public function setAdditionalParameters(array $additionalParameters): void
	{
		$this->additionalParameters = $additionalParameters;
	}

	/**
	 * Getter function for additionalParameters
	 * 
	 * @return array
	 */
	public function getAdditionalParameters(): array
	{
		return $this->additionalParameters;
	}

    /**
     * Add a new additional parameter
     *
     * @param string $key
     * @param object $value
     *
     * @return $this
     */
    public function addAdditionalParameter(string $key, object $value): self
    {
        if ($this->additionalParameters === null) {
            $this->additionalParameters = [];
        }

        $this->additionalParameters[$key] = $value;

        return $this;
    }

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class OriginalCreditRequest {" . PHP_EOL
			. "    merchantRefNum: " . $this->toIndentedString($this->merchantRefNum) . PHP_EOL
			. "    amount: " . $this->toIndentedString($this->amount) . PHP_EOL
			. "    currencyCode: " . $this->toIndentedString($this->currencyCode) . PHP_EOL
			. "    paymentHandleToken: " . $this->toIndentedString($this->paymentHandleToken) . PHP_EOL
			. "    customerIp: " . $this->toIndentedString($this->customerIp) . PHP_EOL
			. "    description: " . $this->toIndentedString($this->description) . PHP_EOL
			. "    merchantDescriptor: " . $this->toIndentedString($this->merchantDescriptor) . PHP_EOL
			. "    paymentFacilitator: " . $this->toIndentedString($this->paymentFacilitator) . PHP_EOL
			. "    additionalParameters: " . $this->toIndentedString($this->additionalParameters) . PHP_EOL
			. "}";
	}
}
