<?php
/** All Rights Reserved, Copyright © Paysafe Holdings UK Limited 2025. For more information see LICENSE */

namespace Paysafe\PhpSdk\Model\OriginalCredit;

use Paysafe\PhpSdk\Model\BaseModel;
use Paysafe\PhpSdk\Model\Card\Card;
use Paysafe\PhpSdk\Model\Card\MerchantDescriptor;
use Paysafe\PhpSdk\Model\Common\BillingDetails;
use Paysafe\PhpSdk\Model\Common\PaymentFacilitator\PaymentFacilitator;

/**
 * OriginalCredit
 */
class OriginalCredit extends BaseModel
{

	private string $merchantRefNum;
	private int $amount;
	private string $currencyCode;
	private string $paymentHandleToken;
	private string $customerIp;
	private string $description;
	private MerchantDescriptor $merchantDescriptor;
	private PaymentFacilitator $paymentFacilitator;
	private string $id;
	private string $paymentType;
	private string $txnTime;
	private BillingDetails $billingDetails;
	private string $status;
	private Card $card;
	private string $cardSchemeTransactionId;

	/**
	 * Builder function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return $this
	 */
	public function merchantRefNum(string $merchantRefNum): self
	{
		$this->setMerchantRefNum($merchantRefNum);
		
		return $this;
	}

	/**
	 * Setter function for merchantRefNum
	 * 
	 * @param string $merchantRefNum
	 * 
	 * @return void
	 */
	public function setMerchantRefNum(string $merchantRefNum): void
	{
		$this->merchantRefNum = $merchantRefNum;
	}

	/**
	 * This is the merchant reference number created by the merchant and submitted as part of the request.
     * It must be unique for each request.
	 * 
	 * @return string
	 */
	public function getMerchantRefNum(): string
	{
		return $this->merchantRefNum;
	}

	/**
	 * Builder function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return $this
	 */
	public function amount(int $amount): self
	{
		$this->setAmount($amount);
		
		return $this;
	}

	/**
	 * Setter function for amount
	 * 
	 * @param int $amount
	 * 
	 * @return void
	 */
	public function setAmount(int $amount): void
	{
		$this->amount = $amount;
	}

	/**
	 * This is the amount of the request, in minor units. For example, to process US $10.99,
     * this value should be 1099.
	 * <b>Note:<b> The amount specified in the Original Credit request must match the amount
     * specified in the Payment Handle
	 * request from which the paymentHandleToken is taken. <br />
	 * <p>
	 * Maximum: 99999999999
	 * 
	 * @return int
	 */
	public function getAmount(): int
	{
		return $this->amount;
	}

	/**
	 * Builder function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return $this
	 */
	public function currencyCode(string $currencyCode): self
	{
		$this->setCurrencyCode($currencyCode);
		
		return $this;
	}

	/**
	 * Setter function for currencyCode
	 * 
	 * @param string $currencyCode
	 * 
	 * @return void
	 */
	public function setCurrencyCode(string $currencyCode): void
	{
		$this->currencyCode = $currencyCode;
	}

	/**
	 * This is the currency of the merchant account, e.g., USD or CAD, returned in the request response.
	 * <p>
	 * See
     * <a
     * href="https://developer.paysafe.com/en/support/reference-information/codes/#currency-codes"
     * >Currency Codes.</a><br />
	 * <b>Note:<b> The currencyCode specified in the Credit request must match the currencyCode specified
     * in the Payment Handle request from
	 * which the paymentHandleToken is taken.
	 * 
	 * @return string
	 */
	public function getCurrencyCode(): string
	{
		return $this->currencyCode;
	}

	/**
	 * Builder function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return $this
	 */
	public function paymentHandleToken(string $paymentHandleToken): self
	{
		$this->setPaymentHandleToken($paymentHandleToken);
		
		return $this;
	}

	/**
	 * Setter function for paymentHandleToken
	 * 
	 * @param string $paymentHandleToken
	 * 
	 * @return void
	 */
	public function setPaymentHandleToken(string $paymentHandleToken): void
	{
		$this->paymentHandleToken = $paymentHandleToken;
	}

	/**
	 * This is the payment token generated by Paysafe that will be used by merchants for Original Credit requests.
	 * 
	 * @return string
	 */
	public function getPaymentHandleToken(): string
	{
		return $this->paymentHandleToken;
	}

	/**
	 * Builder function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return $this
	 */
	public function customerIp(string $customerIp): self
	{
		$this->setCustomerIp($customerIp);
		
		return $this;
	}

	/**
	 * Setter function for customerIp
	 * 
	 * @param string $customerIp
	 * 
	 * @return void
	 */
	public function setCustomerIp(string $customerIp): void
	{
		$this->customerIp = $customerIp;
	}

	/**
	 * This is the customer's IP address.
	 * 
	 * @return string
	 */
	public function getCustomerIp(): string
	{
		return $this->customerIp;
	}

	/**
	 * Builder function for description
	 * 
	 * @param string $description
	 * 
	 * @return $this
	 */
	public function description(string $description): self
	{
		$this->setDescription($description);
		
		return $this;
	}

	/**
	 * Setter function for description
	 * 
	 * @param string $description
	 * 
	 * @return void
	 */
	public function setDescription(string $description): void
	{
		$this->description = $description;
	}

	/**
	 * This is a description of the transaction, provided by the merchant.
	 * 
	 * @return string
	 */
	public function getDescription(): string
	{
		return $this->description;
	}

	/**
	 * Builder function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return $this
	 */
	public function merchantDescriptor(MerchantDescriptor $merchantDescriptor): self
	{
		$this->setMerchantDescriptor($merchantDescriptor);
		
		return $this;
	}

	/**
	 * Setter function for merchantDescriptor
	 * 
	 * @param MerchantDescriptor $merchantDescriptor
	 * 
	 * @return void
	 */
	public function setMerchantDescriptor(MerchantDescriptor $merchantDescriptor): void
	{
		$this->merchantDescriptor = $merchantDescriptor;
	}

	/**
	 * For Card payment method only. This is the merchant descriptor that will be displayed on
     * the customer's card or bank statement.
	 * 
	 * @return MerchantDescriptor
	 */
	public function getMerchantDescriptor(): MerchantDescriptor
	{
		return $this->merchantDescriptor;
	}

	/**
	 * Builder function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return $this
	 */
	public function paymentFacilitator(PaymentFacilitator $paymentFacilitator): self
	{
		$this->setPaymentFacilitator($paymentFacilitator);
		
		return $this;
	}

	/**
	 * Setter function for paymentFacilitator
	 * 
	 * @param PaymentFacilitator $paymentFacilitator
	 * 
	 * @return void
	 */
	public function setPaymentFacilitator(PaymentFacilitator $paymentFacilitator): void
	{
		$this->paymentFacilitator = $paymentFacilitator;
	}

	/**
	 * Contains information about Payment facilitator. <b>Note:<b> This object is only
     * for Payment facilitator merchants.
	 * 
	 * @return PaymentFacilitator
	 */
	public function getPaymentFacilitator(): PaymentFacilitator
	{
		return $this->paymentFacilitator;
	}

	/**
	 * Builder function for id
	 * 
	 * @param string $id
	 * 
	 * @return $this
	 */
	public function id(string $id): self
	{
		$this->setId($id);
		
		return $this;
	}

	/**
	 * Setter function for id
	 * 
	 * @param string $id
	 * 
	 * @return void
	 */
	public function setId(string $id): void
	{
		$this->id = $id;
	}

	/**
	 * This is the ID returned in the response. This ID can be used for future associated requests.
	 * 
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}

	/**
	 * Builder function for paymentType
	 * 
	 * @param string $paymentType
	 * 
	 * @return $this
	 */
	public function paymentType(string $paymentType): self
	{
		$this->setPaymentType($paymentType);
		
		return $this;
	}

	/**
	 * Setter function for paymentType
	 * 
	 * @param string $paymentType
	 * 
	 * @return void
	 */
	public function setPaymentType(string $paymentType): void
	{
		$this->paymentType = $paymentType;
	}

	/**
	 * Get paymentType. Possible value: CARD.
	 * 
	 * @return string
	 */
	public function getPaymentType(): string
	{
		return $this->paymentType;
	}

	/**
	 * Builder function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return $this
	 */
	public function txnTime(string $txnTime): self
	{
		$this->setTxnTime($txnTime);
		
		return $this;
	}

	/**
	 * Setter function for txnTime
	 * 
	 * @param string $txnTime
	 * 
	 * @return void
	 */
	public function setTxnTime(string $txnTime): void
	{
		$this->txnTime = $txnTime;
	}

	/**
	 * This is the date and time the transaction was processed.
	 * 
	 * @return string
	 */
	public function getTxnTime(): string
	{
		return $this->txnTime;
	}

	/**
	 * Builder function for billingDetails
	 * 
	 * @param BillingDetails $billingDetails
	 * 
	 * @return $this
	 */
	public function billingDetails(BillingDetails $billingDetails): self
	{
		$this->setBillingDetails($billingDetails);
		
		return $this;
	}

	/**
	 * Setter function for billingDetails
	 * 
	 * @param BillingDetails $billingDetails
	 * 
	 * @return void
	 */
	public function setBillingDetails(BillingDetails $billingDetails): void
	{
		$this->billingDetails = $billingDetails;
	}

	/**
	 * Customer's billing details. Required if AVS (Address verification) is enabled.<br />
	 * If included in the request, this will serve as the billing address for transaction processing. <br />
	 * 3DS Flow: It is recommended to send billingDetails to improve acceptance rate.
	 * 
	 * @return BillingDetails
	 */
	public function getBillingDetails(): BillingDetails
	{
		return $this->billingDetails;
	}

	/**
	 * Builder function for status
	 * 
	 * @param string $status
	 * 
	 * @return $this
	 */
	public function status(string $status): self
	{
		$this->setStatus($status);
		
		return $this;
	}

	/**
	 * Setter function for status
	 * 
	 * @param string $status
	 * 
	 * @return void
	 */
	public function setStatus(string $status): void
	{
		$this->status = $status;
	}

	/**
	 * This is the status of the payment handle. Possible values are:  <br />
	 * • INITIATED – The transaction was initiated with the downstream provider.  <br />
	 * • RECEIVED - Our system has received the request and is waiting for the downstream processor’s response.
     *      <br />
	 * • PENDING - The transaction awaiting payment service provider's response. <br />
	 * • CANCELLED – The authorization request has been fully reversed. <br />
	 * • EXPIRED – The transaction request is expired. <br />
	 * • COMPLETED – The transaction request is completed.<br />
	 * 
	 * @return string
	 */
	public function getStatus(): string
	{
		return $this->status;
	}

	/**
	 * Builder function for card
	 * 
	 * @param Card $card
	 * 
	 * @return $this
	 */
	public function card(Card $card): self
	{
		$this->setCard($card);
		
		return $this;
	}

	/**
	 * Setter function for card
	 * 
	 * @param Card $card
	 * 
	 * @return void
	 */
	public function setCard(Card $card): void
	{
		$this->card = $card;
	}

	/**
	 * Card details to be used for the transaction
	 * 
	 * @return Card
	 */
	public function getCard(): Card
	{
		return $this->card;
	}

	/**
	 * Builder function for cardSchemeTransactionId
	 * 
	 * @param string $cardSchemeTransactionId
	 * 
	 * @return $this
	 */
	public function cardSchemeTransactionId(string $cardSchemeTransactionId): self
	{
		$this->setCardSchemeTransactionId($cardSchemeTransactionId);
		
		return $this;
	}

	/**
	 * Setter function for cardSchemeTransactionId
	 * 
	 * @param string $cardSchemeTransactionId
	 * 
	 * @return void
	 */
	public function setCardSchemeTransactionId(string $cardSchemeTransactionId): void
	{
		$this->cardSchemeTransactionId = $cardSchemeTransactionId;
	}

	/**
	 * Card details to be used for the transaction
	 * 
	 * @return string
	 */
	public function getCardSchemeTransactionId(): string
	{
		return $this->cardSchemeTransactionId;
	}

	/**
	 * Convert the object to a string representation.
	 * 
	 * @return string
	 */
	public function __toString(): string
	{
		return "class OriginalCredit {" . PHP_EOL
			. "    merchantRefNum: " . $this->toIndentedString($this->merchantRefNum) . PHP_EOL
			. "    amount: " . $this->toIndentedString($this->amount) . PHP_EOL
			. "    currencyCode: " . $this->toIndentedString($this->currencyCode) . PHP_EOL
			. "    paymentHandleToken: " . $this->toIndentedString($this->paymentHandleToken) . PHP_EOL
			. "    customerIp: " . $this->toIndentedString($this->customerIp) . PHP_EOL
			. "    description: " . $this->toIndentedString($this->description) . PHP_EOL
			. "    merchantDescriptor: " . $this->toIndentedString($this->merchantDescriptor) . PHP_EOL
			. "    paymentFacilitator: " . $this->toIndentedString($this->paymentFacilitator) . PHP_EOL
			. "    id: " . $this->toIndentedString($this->id) . PHP_EOL
			. "    paymentType: " . $this->toIndentedString($this->paymentType) . PHP_EOL
			. "    txnTime: " . $this->toIndentedString($this->txnTime) . PHP_EOL
			. "    billingDetails: " . $this->toIndentedString($this->billingDetails) . PHP_EOL
			. "    status: " . $this->toIndentedString($this->status) . PHP_EOL
			. "    card: " . $this->toIndentedString($this->card) . PHP_EOL
			. "    cardSchemeTransactionId: " . $this->toIndentedString($this->cardSchemeTransactionId) . PHP_EOL
			. "}";
	}
}
